//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sorting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sorting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aamir
        ///Aaron
        ///Abbey
        ///Abbie
        ///Abbot
        ///Abbott
        ///Abby
        ///Abdel
        ///Abdul
        ///Abdulkarim
        ///Abdullah
        ///Abe
        ///Abel
        ///Abelard
        ///Abner
        ///Abraham
        ///Abram
        ///Ace
        ///Adair
        ///Adam
        ///Adams
        ///Addie
        ///Adger
        ///Aditya
        ///Adlai
        ///Adnan
        ///Adolf
        ///Adolfo
        ///Adolph
        ///Adolphe
        ///Adolpho
        ///Adolphus
        ///Adrian
        ///Adrick
        ///Adrien
        ///Agamemnon
        ///Aguinaldo
        ///Aguste
        ///Agustin
        ///Aharon
        ///Ahmad
        ///Ahmed
        ///Ahmet
        ///Ajai
        ///Ajay
        ///Al
        ///Alaa
        ///Alain
        ///Alan
        ///Alasdair
        ///Alastair
        ///Albatros
        ///Albert
        ///Alberto
        ///Albrecht
        ///Alden
        ///Aldis
        ///Aldo
        ///Aldric
        ///Aldrich
        ///Aldus
        ///Aldwin
        ///Alec
        ///Aleck
        ///Alejandro
        ///Aleks
        ///Aleks [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string firstNames {
            get {
                return ResourceManager.GetString("firstNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaberg
        ///Aaccf
        ///Aaker
        ///Aamodt
        ///Aardema
        ///Aaren
        ///Aarika
        ///Aaron
        ///Aarons
        ///Aaronson
        ///Aartjan
        ///Aase
        ///Aasen
        ///Abad
        ///Abadie
        ///Abagael
        ///Abagail
        ///Abahri
        ///Abair
        ///Abalos
        ///Abarca
        ///Abare
        ///Abate
        ///Abbas
        ///Abbasi
        ///Abbate
        ///Abbatiello
        ///Abbe
        ///Abbett
        ///Abbey
        ///Abbi
        ///Abbie
        ///Abbitt
        ///Abbot
        ///Abbott
        ///Abboud
        ///Abbruzzese
        ///Abbs
        ///Abby
        ///Abbye
        ///Abdalla
        ///Abdallah
        ///Abdella
        ///Abdo
        ///Abdul
        ///Abdulla
        ///Abdullah
        ///Abe
        ///Abed
        ///Abee
        ///Abel
        ///Abela
        ///Abelard
        ///Abele
        ///Abeles
        ///Abell
        ///Abella
        ///Abeln
        ///Abels
        ///Abelson
        ///Abend
        ///Abendroth
        ///Aber
        ///Abercrombie
        ///Aberg
        ///Aberle        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string surnames {
            get {
                return ResourceManager.GetString("surnames", resourceCulture);
            }
        }
    }
}
